node.environment=ulpf
node.id=ulpf-presto-coordinator-1
node.data-dir=/var/presto/data
node.id=c8be05a2e7c5
node.id=c8be05a2e7c5
node.id=c8be05a2e7c5
node.id=c8be05a2e7c5
node.id=c8be05a2e7c5
node.id=cbff4cbad534
node.id=706fcdb76284
node.id=efe631e5115e
node.id=efe631e5115e
